// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	authservice "github.com/rokwire/core-auth-library-go/authservice"
	mock "github.com/stretchr/testify/mock"
)

// ServiceRegManager is an autogenerated mock type for the ServiceRegManager type
type ServiceRegManager struct {
	mock.Mock
	*authservice.ServiceRegSubscriptions
}

// LoadServices provides a mock function with given fields:
func (_m *ServiceRegManager) LoadServices() ([]authservice.ServiceReg, error) {
	ret := _m.Called()

	var r0 []authservice.ServiceReg
	if rf, ok := ret.Get(0).(func() []authservice.ServiceReg); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]authservice.ServiceReg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceID provides a mock function with given fields:
func (_m *ServiceRegManager) ServiceID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

func NewServiceRegManager(subscribedServices []string) *ServiceRegManager {
	subscriptions := authservice.NewServiceRegSubscriptions(subscribedServices)
	return &ServiceRegManager{ServiceRegSubscriptions: subscriptions}
}
