// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceAccountLoader is an autogenerated mock type for the ServiceAccountLoader type
type ServiceAccountLoader struct {
	mock.Mock
}

// AccessTokenString provides a mock function with given fields:
func (_m *ServiceAccountLoader) AccessTokenString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAccessToken provides a mock function with given fields:
func (_m *ServiceAccountLoader) GetAccessToken() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func NewServiceAccountLoader() *ServiceAccountLoader {
	return &ServiceAccountLoader{}
}
