// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceAccountLoader is an autogenerated mock type for the ServiceAccountLoader type
type ServiceAccountLoader struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields:
func (_m *ServiceAccountLoader) GetAccessToken() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDeletedAccounts provides a mock function with given fields:
func (_m *ServiceAccountLoader) GetDeletedAccounts() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewServiceAccountLoader(subscribedServices []string) *ServiceAccountLoader {
	return &ServiceAccountLoader{}
}